### ISSUE TITLE
Convert bash scripts to Ansible playbooks

### ISSUE THREAD

**Issue by voutilad** [freelawproject/freelawmachine#15]
We've got a slew of shell scripts (bash) that need to be converted to one or many playbooks.

- [x] vagrant.sh (vagrant-specific box config...is this needed?)
- [x] ~~git.sh (updated git client)~~ (does this matter? might punt)
- [x] courtlistener.sh
  - [x] phantomjs stuff for testing
  - [x] automate db migration & setup
  - [x] fix command running `update-seals` since it needs to run inside the virtualenv
- [x] juriscraper.sh
- [x] postresql.sh
- [x] solr.sh
- [x] tesseract.sh
- [x] redis.sh
- [x] celery.sh
- [x] ~~init.sh (various directory and symlink creation)~~ (this will be done as part of the others as it's shared logic)
- [x] ~~zerodisk.sh (is this even needed? was originally to make disk image more compressible I think...)~~ punting on this as it's best done by packer or the like

**Comment by mlissner** [comment]
For Solr, I've got some early work I'm doing. It's for the upgrade, but it'll have similar stuff.

**Comment by voutilad** [comment]
Redis role is implemented using the original FreeLawMachine logic. Caveat is I made a local copy of https://github.com/freelawproject/courtlistener/blob/master/scripts/etc/redis_cl_overrides.conf into this project.

**Comment by voutilad** [comment]
Fun facts currently:

**Running playbook from clean VM state**:
```
PLAY RECAP *********************************************************************
vagrant                    : ok=79   changed=71   unreachable=0    failed=0

./freelawmachine.yml  109.62s user 83.66s system 12% cpu 25:18.25 total
```

**Comment by voutilad** [comment]
*Running playbook from unclean VM State:*
```
PLAY RECAP *********************************************************************
vagrant                    : ok=61   changed=13   unreachable=0    failed=0

./freelawmachine.yml  40.65s user 29.22s system 18% cpu 6:22.51 total
```
