### ISSUE TITLE
Created synced folder for juriscraper; how to populate?

### ISSUE THREAD

**Issue by jon-freed** [freelawproject/freelawmachine#30]
Please create a synced folder for the `juriscraper/pacer` folder just like the synced folder that is already in the freelawmachine for `courtlistener`.

To create the folder, the following line could be added to the `Vagrantfile` configuration file.

```
config.vm.synced_folder "./juriscraper/juriscraper/pacer", "/home/vagrant/.virtualenvs/courtlistener/lib/python2.7/site-packages/juriscraper/pacer", create: true
```

However, I don't personally know yet how to make the `vagrant up` command download/clone a copy of the `juriscraper` repository like it is doing for the `courtlistener` synced folder.  Unless that is done, the above `Vagrantfile` line by itself will lead to errors.

The `juriscraper` repository needs to be downloaded/cloned to be within a `juriscraper` folder that is within the same parent folder as the `Vagrantfile` file.

**Comment by mlissner** [comment]
I'm not sure how Juriscraper is handled at present in freelawmachine, but I *think* it's just coming from pip. It might be OK just to keep it that way and say that if folks want to hack on Juriscraper, there's no need for freelawmachine.

**Comment by jon-freed** [comment]
I'm going to close this request (my request) now that I have a better understanding of what Juriscraper does and why it doesn't necessarily need to be changed for the RECAP search `pro se` option I'm working on.  (`freelawproject\courtlistener` issue #808)

Still, I have this nagging feeling that if somebody wants to do a test of Juriscraper within the flow of data (a) from the RECAP extension, (b) through the CourtListener website (which includes CourtListener's use of Juriscraper), (c) to the database, and then (d) back up to the UI, then a fulfillment of this enhancement request would enable that somebody to do that test without either editing the Vagrantfile or delving into git within the `freelawmachine` `vagrant ssh` session.

**Comment by mlissner** [comment]
I think the test you describe would be possible without doing any git with Juriscraper because Juriscraper is installed as part of CourtListener alongside all the other various libraries it depends on.
