### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by kflaxman** [freelawproject/freelawmachine#44]
I just tried to build courtlistener. On virtualbox 6.0,  vagrant 2.2.5. Ubuntu 18.04.
vagrant up  builds without errors until 

TASK [courtlistener : migrate the database] ************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "./manage.py migrate --noinput", "failed": true, "msg": "\n:stderr: Traceback (most recent call last):\n  File \"./manage.py\", line 10, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line\n    utility.execute()\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 356, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py\", line 283, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py\", line 327, in execute\n    self.check()\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py\", line 359, in check\n    include_deployment_checks=include_deployment_checks,\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py\", line 62, in _run_checks\n    issues.extend(super(Command, self)._run_checks(**kwargs))\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/management/base.py\", line 346, in _run_checks\n    return checks.run_checks(**kwargs)\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/checks/registry.py\", line 81, in run_checks\n    new_errors = check(app_configs=app_configs)\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/checks/urls.py\", line 16, in check_url_config\n    return check_resolver(resolver)\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/checks/urls.py\", line 26, in check_resolver\n    return check_method()\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/urls/resolvers.py\", line 256, in check\n    for pattern in self.url_patterns:\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/urls/resolvers.py\", line 407, in url_patterns\n    patterns = getattr(self.urlconf_module, \"urlpatterns\", self.urlconf_module)\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/utils/functional.py\", line 35, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/urls/resolvers.py\", line 400, in urlconf_module\n    return import_module(self.urlconf_name)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/var/www/courtlistener/cl/urls.py\", line 19, in <module>\n    url('', include('cl.api.urls')),\n  File \"/home/vagrant/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/conf/urls/__init__.py\", line 50, in include\n    urlconf_module = import_module(urlconf_module)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/var/www/courtlistener/cl/api/urls.py\", line 9, in <module>\n    from cl.recap import views as recap_views\n  File \"/var/www/courtlistener/cl/recap/views.py\", line 9, in <module>\n    from cl.recap.tasks import process_recap_upload\n  File \"/var/www/courtlistener/cl/recap/tasks.py\", line 15, in <module>\n    from juriscraper.pacer import AppellateDocketReport, AttachmentPage, \\\nImportError: cannot import name AppellateDocketReport\n", "path": "/home/vagrant/.virtualenvs/courtlistener/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games", "state": "absent", "syspath": ["/tmp/ansible_6aFNRS", "/tmp/ansible_6aFNRS/ansible_modlib.zip", "/tmp/ansible_6aFNRS/ansible_modlib.zip", "/usr/lib/python2.7", "/usr/lib/python2.7/plat-x86_64-linux-gnu", "/usr/lib/python2.7/lib-tk", "/usr/lib/python2.7/lib-old", "/usr/lib/python2.7/lib-dynload", "/usr/local/lib/python2.7/dist-packages", "/usr/lib/python2.7/dist-packages", "/usr/lib/python2.7/dist-packages/PILcompat"]}
        to retry, use: --limit @/vagrant/ansible/freelawbox.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=23   changed=16   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

==============================================
Was something updated but not reflected in the Vagrantfile?

Thanks

**Comment by mlissner** [comment]
Yeah....the vagrantfile is pretty broken and our docs are out of date, and, well, it all needs some love. What are you trying to accomplish?

**Comment by kflaxman** [comment]
I was trying to bring it up on a local machine.
I really want to "customize" (borrow?, certainly not steal)  your solr
stuff and thought the easiest way to understand the package would be to get
a working copy.

Why do I want to do this? I run a mailing list for civil rights lawyers in
Chicago. One of the features is a daily list of decisions from the N.D.Ill
of civil rights and prisoner cases, with a directl link (on my website) to
download. (I have a perl script to download the cases each morning.) I
wanted to add search capabilities to my collection and add other pleadings
to the collection.  I might be reinventing what you guys have done, but I
want something that is less of a jack of all trades.

Thanks for the response.

-ken
-- 
Kenneth N. Flaxman
200 S Michigan Ave, Ste 201
Chicago, IL 60604
(312) 427-3200
(312) 427-3930 (fax)
www.kenlaw.com

**Comment by mlissner** [comment]
Actually, I have *good* news for you then: We pulled all our solr stuff out of the main repo and put it into it's own docker image, over here: https://github.com/freelawproject/courtlistener-solr-server/

That actually *might* be easier to use for you, especially if you use docker, but even if not, it's got everything pulled apart pretty tidily at this point.

**Comment by kflaxman** [comment]
Wow. Thanks.
-ken
Kenneth N. Flaxman
200 S Michigan Ave, Ste 201
Chicago, IL 60604
(312) 427-3200
(312) 427-3930 (fax)
www.kenlaw.com

**Comment by mlissner** [comment]
Closing, but feel free to write emails, open other issues, etc.
